name: github-actions-setup-cli-template
description: GitHub Actions setup CLI template
author: remarkablemark
inputs:
  version:
    description: Description
    required: false
    default: 1.2.3
runs:
  using: node16
  main: dist/index.js
