name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: Lint codebase
        run: npm run lint

      - name: Check type
        run: npm run lint:tsc

      - name: Run tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v3

      - name: Run action
        uses: ./

      - name: Build artifact
        run: npm run build

      - name: Check Git working tree
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Detected uncommitted changes. See status below:'
            git diff
            exit 1
          fi

  # action should work on a clean machine without building
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [1.14.0, 2.27.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run action
        uses: ./
        with:
          cli-version: ${{ matrix.version }}

      - name: Get binary
        run: command -v gh

      - name: Check version
        if: matrix.os != 'windows-latest'
        run: |
          if [[ $(gh --version) != *'${{ matrix.version }}'* ]]; then
            echo 'Version does not match. See version below:'
            gh --version
            exit 1
          fi

      - name: Show help
        run: gh --help
